//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvenueOne.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<Id></Id><FirstName></FirstName><MiddleName></MiddleName><LastName></LastName><Ma" +
            "idenName></MaidenName><Suffix></Suffix><Gender></Gender><CivilStatus></CivilStat" +
            "us><Nationality></Nationality><BirthDate></BirthDate><FullName></FullName>")]
        public global::AvenueOne.Models.Person UserProfile {
            get {
                return ((global::AvenueOne.Models.Person)(this["UserProfile"]));
            }
            set {
                this["UserProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <User>
            <Id>
            </Id>
            <Username>
            </Username>
            <Password>
            </Password>
            <IsAdmin>false</IsAdmin>
            <Person>
            </Person>
          </User>
        ")]
        public global::AvenueOne.Models.User UserAccount {
            get {
                return ((global::AvenueOne.Models.User)(this["UserAccount"]));
            }
            set {
                this["UserAccount"] = value;
            }
        }
    }
}
